# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copywriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('content', models.TextField()),
            ],
        ),
    ]
