# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Copywriting',
            new_name='LandingPage',
        ),
    ]
