# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0002_auto_20160423_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='flesch_kincaid_grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
