# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0004_landingpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='automated_readability_index',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='coleman_liau_index',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='dale_chall_readability_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='flesch_reading_ease',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='gunning_fog',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='linsear_write_formula',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='smog_index',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
