# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copywriting', '0005_auto_20160424_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
